compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

initFields:
  version: 0.0.1
  license: BSD-3-Clause
  type: module

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs

pnpEnableEsmLoader: true
