name: Checks

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  checks:
    uses: atls/shared/.github/workflows/checks.yaml@master
